alunos =[
    {
        "cpd": 35170,
        "idade": 22,
        "aluno": "ANDRE VICTOR PIRES MACHADO",
        "curso": "DIREITO",
        "turma": 60982,
        "notas": 9.730769,
        "faltas": 2,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 1º MELHOR DA SUA TURMA",
        "posicao_ordenada": "1"
    },
    {
        "cpd": 37876,
        "idade": 46,
        "aluno": "ANTONIO DE ANDRADE FERREIRA",
        "curso": "DIREITO",
        "turma": 60982,
        "notas": 9.615384,
        "faltas": 1,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 2º MELHOR DA SUA TURMA",
        "posicao_ordenada": "2"
    },
    {
        "cpd": 41698,
        "idade": 23,
        "aluno": "BIANCA DE CASSIA SOARES RABELO NUNES",
        "curso": "DIREITO",
        "turma": 60881,
        "notas": 9.545454,
        "faltas": 5,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 3º MELHOR DA SUA TURMA",
        "posicao_ordenada": "3"
    },
    {
        "cpd": 53659,
        "idade": 21,
        "aluno": "LORENA BEATRIZ ABREU VIANA",
        "curso": "DIREITO",
        "turma": 60766,
        "notas": 9.500000,
        "faltas": 0,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 4º MELHOR DA SUA TURMA",
        "posicao_ordenada": "4"
    },
    {
        "cpd": 41174,
        "idade": 34,
        "aluno": "ROSSELINE ARAUJO SANTOS PARMA",
        "curso": "DIREITO",
        "turma": 60881,
        "notas": 9.454545,
        "faltas": 5,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 5º MELHOR DA SUA TURMA",
        "posicao_ordenada": "5"
    },
    {
        "cpd": 33257,
        "idade": 30,
        "aluno": "PAULO VINICIUS MOREIRA E SILVA",
        "curso": "DIREITO",
        "turma": 61066,
        "notas": 9.428571,
        "faltas": 0,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 6º MELHOR DA SUA TURMA",
        "posicao_ordenada": "6"
    },
    {
        "cpd": 26061,
        "idade": 25,
        "aluno": "AMANDHA CAROLLINE SILVA SANTOS",
        "curso": "DIREITO",
        "turma": 61066,
        "notas": 9.428571,
        "faltas": 3,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 7º MELHOR DA SUA TURMA",
        "posicao_ordenada": "7"
    },
    {
        "cpd": 32361,
        "idade": 24,
        "aluno": "IVA RAQUEL  SANTOS JACINTO FONSECA ",
        "curso": "DIREITO",
        "turma": 60982,
        "notas": 9.384615,
        "faltas": 2,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 8º MELHOR DA SUA TURMA",
        "posicao_ordenada": "8"
    },
    {
        "cpd": 26162,
        "idade": 24,
        "aluno": "ALLYNE WALNNA CUTRIM OLIVEIRA",
        "curso": "DIREITO",
        "turma": 61066,
        "notas": 9.357142,
        "faltas": 3,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 9º MELHOR DA SUA TURMA",
        "posicao_ordenada": "9"
    },
    {
        "cpd": 33260,
        "idade": 57,
        "aluno": "ORLANDO LUIS LEITE ROCHA",
        "curso": "DIREITO",
        "turma": 60981,
        "notas": 9.346153,
        "faltas": 2,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 10º MELHOR DA SUA TURMA",
        "posicao_ordenada": "10"
    },
    {
        "cpd": 54245,
        "idade": 22,
        "aluno": "RODOLFO JORGE TAVARES DE SOUZA JUNIOR",
        "curso": "DIREITO",
        "turma": 60766,
        "notas": 9.318181,
        "faltas": 0,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 11º MELHOR DA SUA TURMA",
        "posicao_ordenada": "11"
    },
    {
        "cpd": 81254,
        "idade": 21,
        "aluno": "KARLA REGINA SODRE SOBRAL",
        "curso": "DIREITO",
        "turma": 60381,
        "notas": 9.272727,
        "faltas": 3,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 12º MELHOR DA SUA TURMA",
        "posicao_ordenada": "12"
    },
    {
        "cpd": 70229,
        "idade": 21,
        "aluno": "CARLA ISABEL BALDEZ DOS ANJOS",
        "curso": "DIREITO",
        "turma": 60566,
        "notas": 9.272727,
        "faltas": 4,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 13º MELHOR DA SUA TURMA",
        "posicao_ordenada": "13"
    },
    {
        "cpd": 36401,
        "idade": 32,
        "aluno": "SAMUEL SÁ MENEZES MORAES",
        "curso": "DIREITO",
        "turma": 61081,
        "notas": 9.250000,
        "faltas": 6,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 14º MELHOR DA SUA TURMA",
        "posicao_ordenada": "14"
    },
    {
        "cpd": 53393,
        "idade": 25,
        "aluno": "MARCELO REBELO MOCHEL",
        "curso": "DIREITO",
        "turma": 60766,
        "notas": 9.227272,
        "faltas": 0,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 15º MELHOR DA SUA TURMA",
        "posicao_ordenada": "15"
    },
    {
        "cpd": 26151,
        "idade": 24,
        "aluno": "SAMANTHA FRAZAO CRUZ GODOY",
        "curso": "DIREITO",
        "turma": 61066,
        "notas": 9.214285,
        "faltas": 0,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 16º MELHOR DA SUA TURMA",
        "posicao_ordenada": "16"
    },
    {
        "cpd": 85737,
        "idade": 20,
        "aluno": "VICTOR GABRIEL DOS SANTOS FERREIRA",
        "curso": "DIREITO",
        "turma": 60281,
        "notas": 9.200000,
        "faltas": 3,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 17º MELHOR DA SUA TURMA",
        "posicao_ordenada": "17"
    },
    {
        "cpd": 25863,
        "idade": 24,
        "aluno": "LICIA FERNANDA SANTANA DE SOUSA CAMPELO",
        "curso": "DIREITO",
        "turma": 61066,
        "notas": 9.142857,
        "faltas": 0,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 18º MELHOR DA SUA TURMA",
        "posicao_ordenada": "18"
    },
    {
        "cpd": 26056,
        "idade": 37,
        "aluno": "IDENEILTON PEREIRA FONSECA",
        "curso": "DIREITO",
        "turma": 61081,
        "notas": 9.142857,
        "faltas": 6,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 19º MELHOR DA SUA TURMA",
        "posicao_ordenada": "19"
    },
    {
        "cpd": 56511,
        "idade": 34,
        "aluno": "LUCYCLEITON SERRA BARBOSA",
        "curso": "DIREITO",
        "turma": 60782,
        "notas": 9.136363,
        "faltas": 3,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 20º MELHOR DA SUA TURMA",
        "posicao_ordenada": "20"
    },
    {
        "cpd": 79701,
        "idade": 19,
        "aluno": "GABRIELLE BARBOSA ALVES DOS SANTOS",
        "curso": "DIREITO",
        "turma": 60366,
        "notas": 9.136363,
        "faltas": 3,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 21º MELHOR DA SUA TURMA",
        "posicao_ordenada": "21"
    },
    {
        "cpd": 33841,
        "idade": 40,
        "aluno": "SÍVORY AUGUSTO COSTA DE MORAIS",
        "curso": "DIREITO",
        "turma": 60981,
        "notas": 9.115384,
        "faltas": 2,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 22º MELHOR DA SUA TURMA",
        "posicao_ordenada": "22"
    },
    {
        "cpd": 79271,
        "idade": 20,
        "aluno": "ZOROASTRO DE JESUS PEREIRA SOUSA",
        "curso": "DIREITO",
        "turma": 60366,
        "notas": 9.090909,
        "faltas": 0,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 23º MELHOR DA SUA TURMA",
        "posicao_ordenada": "23"
    },
    {
        "cpd": 84962,
        "idade": 34,
        "aluno": "FRANCISCO DAS CHAGAS OLIVEIRA SOBRINHO",
        "curso": "DIREITO",
        "turma": 60281,
        "notas": 9.050000,
        "faltas": 1,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 24º MELHOR DA SUA TURMA",
        "posicao_ordenada": "24"
    },
    {
        "cpd": 77920,
        "idade": 22,
        "aluno": "ANY HELLEN PENHA DE AGUIAR",
        "curso": "DIREITO",
        "turma": 60381,
        "notas": 9.045454,
        "faltas": 0,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 25º MELHOR DA SUA TURMA",
        "posicao_ordenada": "25"
    },
    {
        "cpd": 41167,
        "idade": 24,
        "aluno": "KARINE DOS PASSOS NUNES",
        "curso": "DIREITO",
        "turma": 60881,
        "notas": 9.045454,
        "faltas": 5,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 26º MELHOR DA SUA TURMA",
        "posicao_ordenada": "26"
    },
    {
        "cpd": 31746,
        "idade": 30,
        "aluno": "JOELSON GONÇALVES MARTINS ",
        "curso": "DIREITO",
        "turma": 60981,
        "notas": 9.038461,
        "faltas": 5,
        "qtd_provas_substitutivas": 0,
        "posicao": "O 27º MELHOR DA SUA TURMA",
        "posicao_ordenada": "27"
    }]